submissions/description/cross_site_scripting_xss/reflected/non_self/recommendations.md, submissions/description/cross_site_scripting_xss/reflected/non_self/template.md
* More information about what reflected XSS is in the overview
* Renamed headings
* Moved Business Impact heading up to sit under Overview of the Vulnerability
* Added further details into Steps to Reproduce
=> Updates to Reflected XSS Non-Self

submissions/description/broken_authentication_and_session_management/failure_to_invalidate_session/on_password_change/guidance.md, submissions/description/broken_authentication_and_session_management/failure_to_invalidate_session/on_password_change/recommendations.md, submissions/description/broken_authentication_and_session_management/failure_to_invalidate_session/on_password_change/template.md
* Added info into template.md
* Added a recommendations.md
* Moved guidance to guidance.md
=> updates to Failure to Invalid Session on Password Change finding

submissions/description/broken_authentication_and_session_management/authentication_bypass/guidance.md, submissions/description/broken_authentication_and_session_management/authentication_bypass/recommendations.md, submissions/description/broken_authentication_and_session_management/authentication_bypass/template.md
* Additional information in templates.md
* Added guidance.md
* Added recommendations.md
=> updates to Authentication Bypass finding

submissions/description/sensitive_data_exposure/guidance.md, submissions/description/sensitive_data_exposure/recommendations.md, submissions/description/sensitive_data_exposure/template.md
=> Updates to Sensitive Data Exposure base finding

submissions/description/sensitive_data_exposure/disclosure_of_secrets/guidance.md, submissions/description/sensitive_data_exposure/disclosure_of_secrets/recommendations.md, submissions/description/sensitive_data_exposure/disclosure_of_secrets/template.md
* Removal of placeholders
*Updates to Business Impact
=> Updates to Disclosure of Secrets Finding

submissions/description/sensitive_data_exposure/disclosure_of_secrets/for_internal_asset/recommendations.md, submissions/description/sensitive_data_exposure/disclosure_of_secrets/for_internal_asset/template.md
* Removed placeholder text
*updated business impact
=> Updates to Disclosure of Secrets for Internal Asset

submissions/description/sensitive_data_exposure/disclosure_of_secrets/for_publicly_accessible_asset/recommendations.md, submissions/description/sensitive_data_exposure/disclosure_of_secrets/for_publicly_accessible_asset/template.md
* removal of placeholder text
* Updates to Business impact
=> Disclosure of Secrets - Publicly Accessible Asset

submissions/description/server_security_misconfiguration/no_rate_limiting_on_form/login/recommendations.md, submissions/description/server_security_misconfiguration/no_rate_limiting_on_form/login/template.md
* additional info added to template
* guidance will be captured in parent directory
* recommendations captured in seperate file
=> Updates to No Rate Limiting on Login Form finding

submissions/description/server_security_misconfiguration/no_rate_limiting_on_form/registration/recommendations.md, submissions/description/server_security_misconfiguration/no_rate_limiting_on_form/registration/template.md
* Updated info in template
* recommendations added to separate file
* guidance info in parent folder file
=> updates to No Rate Limiting on Registration Form finding

submissions/description/broken_authentication_and_session_management/privilege_escalation/guidance.md, submissions/description/broken_authentication_and_session_management/privilege_escalation/recommendations.md, submissions/description/broken_authentication_and_session_management/privilege_escalation/template.md
* Made changes to template.md and added in more detail around broken auth, steps to reproduce, and impact of finding
* Added guidance.md file
* Added recommendations within recommendations.md file
=> Updates to Broken Auth Allows Privilege Escalation finding

submissions/description/server_security_misconfiguration/directory_listing_enabled/sensitive_data_exposure/guidance.md, submissions/description/server_security_misconfiguration/directory_listing_enabled/sensitive_data_exposure/recommendations.md, submissions/description/server_security_misconfiguration/directory_listing_enabled/sensitive_data_exposure/template.md
* revision of overview, business impact and steps to reproduce
* Updates to guidance and recommnedations
=> Updates to Directory Listing Enabled based on peer review

submissions/description/cross_site_scripting_xss/stored/privileged_user_to_privilege_elevation/recommendations.md, submissions/description/cross_site_scripting_xss/stored/privileged_user_to_privilege_elevation/template.md
* revised overview, business impact, and steps to repro based on peer feedback
=> Updated Stored XSS (Priv User to Priv Elevation)

submissions/description/cross_site_scripting_xss/reflected/guidance.md, submissions/description/cross_site_scripting_xss/reflected/recommendations.md, submissions/description/cross_site_scripting_xss/reflected/template.md
High level finding updated based on peer review
* updates to overview, steps to repro, business impact
* removal of placeholder text
=> Updates to Reflected Cross-Site Scripting

submissions/description/cross_site_scripting_xss/stored/non_admin_to_anyone/recommendations.md, submissions/description/cross_site_scripting_xss/stored/non_admin_to_anyone/template.md
Updates based on peer review
* Overview, business impact and steps to repro revised
* removal of placeholder text
=> Updates to Stored XSS (non-priv to anyone)

submissions/description/cross_site_scripting_xss/reflected/self/guidance.md, submissions/description/cross_site_scripting_xss/reflected/self/recommendations.md, submissions/description/cross_site_scripting_xss/reflected/self/template.md
* revision of overview, business impact and steps to repro
=> Updates to Self-Reflected XSS

submissions/description/server_security_misconfiguration/directory_listing_enabled/non_sensitive_data_exposure/guidance.md, submissions/description/server_security_misconfiguration/directory_listing_enabled/non_sensitive_data_exposure/recommendations.md, submissions/description/server_security_misconfiguration/directory_listing_enabled/non_sensitive_data_exposure/template.md
Updates made from feedback during peer review
* revision of overview, business impact and steps to reproduce
=> Non-sensitive data exposed via directory listing

submissions/description/server_security_misconfiguration/no_rate_limiting_on_form/email_triggering/guidance.md, submissions/description/server_security_misconfiguration/no_rate_limiting_on_form/email_triggering/recommendations.md, submissions/description/server_security_misconfiguration/no_rate_limiting_on_form/email_triggering/template.md
* Updated wording in template
* Moved guidance to seperate file
* Added recommendations
=> Updates to No Rate Limiting on Form Triggers Emails finding

submissions/description/server_security_misconfiguration/no_rate_limiting_on_form/guidance.md, submissions/description/server_security_misconfiguration/no_rate_limiting_on_form/recommendations.md, submissions/description/server_security_misconfiguration/no_rate_limiting_on_form/template.md
* Updates to templates
* moved guidance to separate doc
* created recommendations file
=> updates to No Rate Limiting on Form

submissions/description/broken_access_control/guidance.md, submissions/description/broken_access_control/recommendations.md, submissions/description/broken_access_control/template.md
The following changes were made:
* Added information to template
* Added Guidance.md file
* Added Recommendations.md file
=> updates to Generic Broken Access Control

submissions/description/server_side_injection/sql_injection/guidance.md, submissions/description/server_side_injection/sql_injection/recommendations.md, submissions/description/server_side_injection/sql_injection/template.md
The following updates have been made to the SQLi finding:
Standardised grammar and flow of findings
Removed JSON guidance from within the templates.md file and created a seperate file
Added a recommendations.md file for future use and drafted some content.
=> Updates to SQLi Finding

submissions/description/broken_access_control/idor/Guidance.md, submissions/description/broken_access_control/idor/Recommendations.md, submissions/description/broken_access_control/idor/template.md
The following updates have been made to the IDOR finding:
Standardised grammar and flow of findings
Removed JSON guidance from within the templates.md file and created a seperate file
Added a recommendations.md file for future use and drafted some content.
=> Updated IDOR Finding

submissions/description/server_security_misconfiguration/no_rate_limiting_on_form/sms_triggering/recommendations.md, submissions/description/server_security_misconfiguration/no_rate_limiting_on_form/sms_triggering/template.md
* updates to template
* added recommendations
* guidance is within separate file in parent folder
=> updates to No Rate Limiting Triggers SMS

submissions/description/broken_authentication_and_session_management/guidance.md, submissions/description/broken_authentication_and_session_management/recommendations.md, submissions/description/broken_authentication_and_session_management/template.md
* Additional info in template
* Moved guidance to guidance.md file for this finding and all sub findings under broken auth and session management
* Still to finalise recommendations.md
=> updates to generic Broken Auth and Session Management finding

submissions/description/cross_site_scripting_xss/cross_site_request_forgery_csrf/flash_based/high_impact/recommendations.md, submissions/description/cross_site_scripting_xss/cross_site_request_forgery_csrf/flash_based/high_impact/template.md
Updates to Template.md file with a breakout of recommendations
=> High Impact Flash-Based CSRF updates

submissions/description/cross_site_scripting_xss/cross_site_request_forgery_csrf/flash_based/low_impact/recommendations.md, submissions/description/cross_site_scripting_xss/cross_site_request_forgery_csrf/flash_based/low_impact/template.md
update to template.md with breakout recommendations
=> Low Impact Flash-Based CSRF updates

submissions/description/server_security_misconfiguration/lack_of_security_headers/guidance.md, submissions/description/server_security_misconfiguration/lack_of_security_headers/strict_transport_security/recommendations.md, submissions/description/server_security_misconfiguration/lack_of_security_headers/strict_transport_security/template.md
* Significant update to template.md 
* addition of recommendations.md
=> Updated lack of HSTS header finding

submissions/description/server_security_misconfiguration/no_rate_limiting_on_form/change_password/recommendations.md, submissions/description/server_security_misconfiguration/no_rate_limiting_on_form/change_password/template.md
=> Further updates to replace PR83

submissions/description/broken_authentication_and_session_management/failure_to_invalidate_session/on_logout_server_side_only/recommendations.md, submissions/description/broken_authentication_and_session_management/failure_to_invalidate_session/on_logout_server_side_only/template.md
=> Failure to Invalidate Session on Logout Server-Side

submissions/description/sensitive_data_exposure/via_localstorage_sessionstorage/sensitive_token/recommendations.md, submissions/description/sensitive_data_exposure/via_localstorage_sessionstorage/sensitive_token/template.md
This PR is Sensitive Token Exposed, a sub finding of Sensitive Data Exposed from PR 160
=> Sensitive Token Exposed in Local or Session Storage

submissions/description/server_side_injection/remote_code_execution_rce/guidance.md, submissions/description/server_side_injection/remote_code_execution_rce/recommendations.md, submissions/description/server_side_injection/remote_code_execution_rce/template.md
This is a quick patch to fix RCE for the main branch, as it was removed in a previous PR (106), and updating the guidance to improve it slightly (written by @vortexau)
=> Fixing RCE

submissions/description/cross_site_scripting_xss/client_side_injection/binary_planting/recommendations.md, submissions/description/cross_site_scripting_xss/client_side_injection/recommendations.md, submissions/description/cross_site_scripting_xss/client_side_injection/template.md
Also fixed formatting on Recommendation for Binary Planting
=> Updates to Client-Side Injection

README.md
Changed the example of a finding to match the new template structure
=> Update to README.md to align with template updates

submissions/description/cross_site_scripting_xss/stored/privileged_user_to_privilege_elevation/template.md
* I accidentally uploaded the old template instead of the refreshed version I rewrote
=> Updated template

submissions/description/broken_authentication_and_session_management/failure_to_invalidate_session/on_password_change/template.md
Changes made to make it clearer that different browsers are being used. e.g. Chrome and Firefox.
=> Updates to steps to reproduce

submissions/description/server_security_misconfiguration/no_rate_limiting_on_form/guidance.md
Tweaks to further explain the required successful exploitation of the lack of rate limiting on a form.
=> Update to Guidance

submissions/description/server_security_misconfiguration/no_rate_limiting_on_form/login/template.md
Added additional information around demonstrating >400 login attempts with a successful login completed
=> Updates to steps to reproduce and PoC template

submissions/description/cryptographic_weakness/insecure_implementation/guidance.md, submissions/description/cryptographic_weakness/insecure_implementation/improper_following_of_specification/guidance.md, submissions/description/cryptographic_weakness/insecure_implementation/improper_following_of_specification/recommendations.md, submissions/description/cryptographic_weakness/insecure_implementation/improper_following_of_specification/template.md, submissions/description/cryptographic_weakness/insecure_implementation/missing_cryptographic_step/guidance.md, submissions/description/cryptographic_weakness/insecure_implementation/missing_cryptographic_step/recommendations.md, submissions/description/cryptographic_weakness/insecure_implementation/missing_cryptographic_step/template.md, submissions/description/cryptographic_weakness/insecure_implementation/recommendations.md, submissions/description/cryptographic_weakness/insecure_implementation/template.md
As per the VRT update in 352 - [bugcrowd/vulnerability-rating-taxonomy#352](https://github.com/bugcrowd/vulnerability-rating-taxonomy/pull/352)
=> Addition of Insecure Implementation subcategory and variants

submissions/description/cryptographic_weakness/insecure_key_generation/guidance.md, submissions/description/cryptographic_weakness/insecure_key_generation/improper_asymmetric_exponent_selection/guidance.md, submissions/description/cryptographic_weakness/insecure_key_generation/improper_asymmetric_exponent_selection/recommendations.md, submissions/description/cryptographic_weakness/insecure_key_generation/improper_asymmetric_exponent_selection/template.md, submissions/description/cryptographic_weakness/insecure_key_generation/improper_asymmetric_prime_selection/guidance.md, submissions/description/cryptographic_weakness/insecure_key_generation/improper_asymmetric_prime_selection/recommendations.md, submissions/description/cryptographic_weakness/insecure_key_generation/improper_asymmetric_prime_selection/template.md, submissions/description/cryptographic_weakness/insecure_key_generation/insufficient_key_space/guidance.md, submissions/description/cryptographic_weakness/insecure_key_generation/insufficient_key_space/recommendations.md, submissions/description/cryptographic_weakness/insecure_key_generation/insufficient_key_space/template.md, submissions/description/cryptographic_weakness/insecure_key_generation/insufficient_key_stretching/guidance.md, submissions/description/cryptographic_weakness/insecure_key_generation/insufficient_key_stretching/recommendations.md, submissions/description/cryptographic_weakness/insecure_key_generation/insufficient_key_stretching/template.md, submissions/description/cryptographic_weakness/insecure_key_generation/key_exchange_without_entity_authentication/guidance_ea.md, submissions/description/cryptographic_weakness/insecure_key_generation/key_exchange_without_entity_authentication/recommendations_ea.md, submissions/description/cryptographic_weakness/insecure_key_generation/key_exchange_without_entity_authentication/template_ea.md, submissions/description/cryptographic_weakness/insecure_key_generation/recommendations.md, submissions/description/cryptographic_weakness/insecure_key_generation/template.md
=> Addition of Insecure Key Generation

submissions/description/cryptographic_weakness/key_reuse/guidance.md, submissions/description/cryptographic_weakness/key_reuse/inter-environment/guidance.md, submissions/description/cryptographic_weakness/key_reuse/inter-environment/recommendations.md, submissions/description/cryptographic_weakness/key_reuse/inter-environment/template.md, submissions/description/cryptographic_weakness/key_reuse/intra-environment/guidance.md, submissions/description/cryptographic_weakness/key_reuse/intra-environment/recommendations.md, submissions/description/cryptographic_weakness/key_reuse/intra-environment/template.md, submissions/description/cryptographic_weakness/key_reuse/lack_of_perfect_forward_secrecy/guidance.md, submissions/description/cryptographic_weakness/key_reuse/lack_of_perfect_forward_secrecy/recommendations.md, submissions/description/cryptographic_weakness/key_reuse/lack_of_perfect_forward_secrecy/template.md, submissions/description/cryptographic_weakness/key_reuse/recommendations.md, submissions/description/cryptographic_weakness/key_reuse/template.md
=> Addition of Key Reuse

submissions/description/cryptographic_weakness/side-channel_attack/differential_fault_analysis/guidance.md, submissions/description/cryptographic_weakness/side-channel_attack/differential_fault_analysis/recommendations.md, submissions/description/cryptographic_weakness/side-channel_attack/differential_fault_analysis/template.md, submissions/description/cryptographic_weakness/side-channel_attack/emanations_attack /guidance.md, submissions/description/cryptographic_weakness/side-channel_attack/emanations_attack /recommendations.md, submissions/description/cryptographic_weakness/side-channel_attack/emanations_attack /template.md, submissions/description/cryptographic_weakness/side-channel_attack/guidance.md, submissions/description/cryptographic_weakness/side-channel_attack/padding_oracle_attack/guidance.md, submissions/description/cryptographic_weakness/side-channel_attack/padding_oracle_attack/recommendations.md, submissions/description/cryptographic_weakness/side-channel_attack/padding_oracle_attack/template.md, submissions/description/cryptographic_weakness/side-channel_attack/power_analysis_attack/guidance.md, submissions/description/cryptographic_weakness/side-channel_attack/power_analysis_attack/recommendations.md, submissions/description/cryptographic_weakness/side-channel_attack/power_analysis_attack/template.md, submissions/description/cryptographic_weakness/side-channel_attack/recommendations.md, submissions/description/cryptographic_weakness/side-channel_attack/template.md, submissions/description/cryptographic_weakness/side-channel_attack/timing_attack/guidance.md, submissions/description/cryptographic_weakness/side-channel_attack/timing_attack/recommendations.md, submissions/description/cryptographic_weakness/side-channel_attack/timing_attack/template.md
=> Addition of Side Channel Attack

submissions/description/cryptographic_weakness/incomplete_cleanup_of_keying_material/guidance.md, submissions/description/cryptographic_weakness/incomplete_cleanup_of_keying_material/recommendations.md, submissions/description/cryptographic_weakness/incomplete_cleanup_of_keying_material/template.md
=> Adding Incomplete Cleanup of Keying Material

submissions/description/cryptographic_weakness/broken_cryptography/guidance.md, submissions/description/cryptographic_weakness/broken_cryptography/recommendations.md, submissions/description/cryptographic_weakness/broken_cryptography/template.md
As per the VRT update in 352 - bugcrowd/vulnerability-rating-taxonomy#352
=> Added Broken Cryptography

submissions/description/cryptographic_weakness/use_of_broken_cryptographic_primitive/guidance.md, submissions/description/cryptographic_weakness/use_of_broken_cryptographic_primitive/recommendations.md, submissions/description/cryptographic_weakness/use_of_broken_cryptographic_primitive/template.md
=> Adding Use of Broken Cryptographic Primitive

submissions/description/cryptographic_weakness/use_of_vulnerable_cryptographic_library/guidance.md, submissions/description/cryptographic_weakness/use_of_vulnerable_cryptographic_library/recommendations.md, submissions/description/cryptographic_weakness/use_of_vulnerable_cryptographic_library/template.md
=> Adding Use of Vulnerable Cryptographic Library

submissions/description/server_side_injection/content_spoofing/html_content_injection/guidance.md, submissions/description/server_side_injection/content_spoofing/html_content_injection/recommendations.md, submissions/description/server_side_injection/content_spoofing/html_content_injection/template.md
* Added new HTML Content Injection template, as per VRT update - https://github.com/bugcrowd/vulnerability-rating-taxonomy/pull/372
* Updated server_side_injection.content_spoofing guidance file as it was referring to the incorrect vulnerability type
=> Added HTML Content Injection template

submissions/description/cryptographic_weakness/insecure_key_generation/improper_asymmetric_exponent_selection/template.md, submissions/description/cryptographic_weakness/insecure_key_generation/improper_asymmetric_prime_selection/template.md, submissions/description/cryptographic_weakness/insecure_key_generation/insufficient_key_space/template.md, submissions/description/cryptographic_weakness/insecure_key_generation/insufficient_key_stretching/template.md
Some simple grammar fixes for the Insecure Key Generation variants
=> Grammar fix

submissions/description/sensitive_data_exposure/json_hijacking/recommendations.md, submissions/description/sensitive_data_exposure/json_hijacking/template.md
Updated template and recommendation
=> Updates to JSON hijacking

submissions/description/sensitive_data_exposure/internal_ip_disclosure/recommendations.md, submissions/description/sensitive_data_exposure/internal_ip_disclosure/template.md
Tweaked the template description and recommendation to be more specific
=> Minor updates to Internal IP address Disclosure

submissions/description/sensitive_data_exposure/non_sensitive_token_in_url/recommendations.md, submissions/description/sensitive_data_exposure/non_sensitive_token_in_url/template.md
Updated Template heading and recommendation
=> Updates to Non-Sensitive Token in URL

submissions/description/server_security_misconfiguration/lack_of_security_headers/cache_control_for_a_sensitive_page/template.md
Updated Steps to Reproduce so that both the missing Cache-Control header is shown as well as sensitive details within the cache
=> Update template.md for Cache Control of a Sensitive Page

submissions/description/broken_authentication_and_session_management/template.md
Created newline at end of .md file to satisfy the linter
=> Broken Auth and Session Management

submissions/description/external_behavior/system_clipboard_leak/recommendations.md, submissions/description/external_behavior/system_clipboard_leak/shared_links/recommendations.md, submissions/description/external_behavior/system_clipboard_leak/shared_links/template.md, submissions/description/external_behavior/system_clipboard_leak/template.md
Updated both the template.md and the recommendation.md files for parent and child variants.
=> Updates to System Clipboard Leaks

submissions/description/broken_authentication_and_session_management/session_fixation/local_attack_vector/recommendations.md, submissions/description/broken_authentication_and_session_management/session_fixation/recommendations.md, submissions/description/broken_authentication_and_session_management/session_fixation/remote_attack_vector/recommendations.md
(The same recommendation text is used across all three)
=> Updates to recommendations for All three session fixation variants

submissions/description/sensitive_data_exposure/disclosure_of_secrets/pii_leakage_exposure/template.md
Updated wording within template to more accurately describe PII and business impact of PII exposure
=> Update wording of PII exposure
